### PR TITLE
Add explicit type annotation to function def

### PR DESCRIPTION
**Pull request by rudolfduplessis**

### CODE REVIEW

**Comment by scottweaver** [comment]
LGMT, thanks!

**Comment by scottweaver** [comment]
Due to the invariant nature of `Has`, line `105` also needs to be changed to `Has(jdbcInfo) ++ Has[Connection](conn) ++ Has[DataSource](dataSource) ++ Has(container)`.

This should fix the test failures.

**Comment by rudolfduplessis** [comment]
Right, but errrm, so yes the invariant nature of `Has`. So if we do that it's going to fail again when accessing it with `ZIO.service[Connection with AutoCloseable]`. Which is what the api states the user should do...as per `type Provides` definition. So I figure, the decision is up to you whether to expose it as `Has[Connection]` or `Has[Connection with AutoCloseable]`. Hold the door. Think I get what happened. I saw Has[Connection with AutoCloseable], and out of "habbit" ('cause of `Has` invariance) I plucked it from the environment as it's been declared and did `ZIO.service[Connection with AutoCloseable]` to get the connection. But I bet you never do that...you just go `ZIO.service[Connection]` and it works, 'cause that's the type inferred and tagged.
So yea, I don't know. I thought it was strange to have to say  `ZIO.service[Connection with AutoCloseable]` in stead of just `ZIO.service[Connection]`. If its not absolutely necessary to declare it with AutoCloseable in `Provides`, then I'd vote for taking it out to avoid this confusion. Connection already is an AutoCloseable.
What do you make of this book I've written? :)

**Comment by rudolfduplessis** [comment]
Made a commit with AutoCloseable removed for your consideration

**Comment by rudolfduplessis** [comment]
Any news about this?

**Review by scottweaver — APPROVED** [review]

**Comment by scottweaver** [comment]
Sorry for the delay.  It's now merged, I will look to publish an 0.9.0 release in the near future.

**Pull request merged**
